/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({
    enabled: true,
    disableCaching : false,
	paths : {
		"Xixixi.model" : 'adminPage/app/model',
		"Xixixi.store" : 'adminPage/app/store',
		"Xixixi.view" : 'adminPage/app/view'
	}
});

Ext.application({
    models: [
        'UserListModel',
        'DepartmentListModel'
    ],
    stores: [
        'GetUserNameStore',
        'UserListStore'
    ],
    views: [
        'AdminViewport',
        'AddUser'
    ],
    name: 'Xixixi',

    launch: function() {
        Ext.create('Xixixi.view.AdminViewport');
    }

});
