/*
 * File: app/view/AddDepartment.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Xixixi.view.AddDepartment', {
    extend: 'Ext.window.Window',
    alias: 'widget.adddepartment',

    requires: [
        'Xixixi.view.AddDepartmentViewModel',
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.XTemplate',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'adddepartment'
    },
    defaultListenerScope: true,
    autoShow: true,
    height: 200,
    hidden: false,
    id: 'addDepartmentWindow',
    maxWidth: 350,
    minHeight: 150,
    width: 300,
    title: '添加部门',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'form',
            flex: 1,
            id: 'addDepartmentForm',
            margin: '10 10 10 10 ',
            modelValidation: false,
            bodyPadding: 10,
            bodyStyle: 'background:#DFE8F6;\r\nborder:1px solid #B5B8C8',
            header: false,
            title: 'My Form',
            items: [
                {
                    xtype: 'textfield',
                    id: 'departmentName',
                    itemId: 'departmentName',
                    maxWidth: 260,
                    modelValidation: true,
                    width: 260,
                    fieldLabel: '部门名称',
                    labelAlign: 'right',
                    labelPad: 10,
                    labelWidth: 70,
                    msgTarget: 'under',
                    name: 'departmentName',
                    allowBlank: false,
                    allowOnlyWhitespace: false,
                    blankText: '必填项',
                    validateBlank: true,
                    listeners: {
                        blur: 'onDepartmentNameBlur'
                    }
                },
                {
                    xtype: 'textfield',
                    id: 'departmentDesc',
                    itemId: 'departmentDesc',
                    maxWidth: 260,
                    width: 260,
                    fieldLabel: '部门描述',
                    labelAlign: 'right',
                    labelPad: 10,
                    labelWidth: 70,
                    name: 'departmentDesc'
                },
                {
                    xtype: 'container',
                    height: 60,
                    margin: '10 10 10 10',
                    layout: {
                        type: 'hbox',
                        align: 'stretch',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'button',
                            flex: 1,
                            id: 'addDepSubmit',
                            itemId: 'addDepSubmit',
                            margin: '15 10 15  0',
                            maxWidth: 50,
                            width: 50,
                            text: '提交',
                            listeners: {
                                click: 'onAdddepartmentsubmitClick'
                            }
                        },
                        {
                            xtype: 'button',
                            flex: 1,
                            id: 'addDepReset',
                            itemId: 'addDepReset',
                            margin: '15 10 15 0',
                            maxWidth: 50,
                            width: 50,
                            text: '重置',
                            listeners: {
                                click: 'onAddDepResetClick'
                            }
                        }
                    ]
                }
            ]
        }
    ],

    onDepartmentNameBlur: function(component, event, eOpts) {
        var departmentName = component.getValue();
        this.validateDepName(departmentName);
    },

    onAdddepartmentsubmitClick: function(button, e, eOpts) {
          var win = button.up('window');
                var form = win.down('form').getForm();
        if(form.isValid()){

                    var jsonData = Ext.JSON.encode(form.getValues());
                    Ext.Ajax.setTimeout(40000);
                    Ext.Ajax.request({
                        url: 'admin/depCreateOrEdit.action',
                        method : 'POST',
                        headers : {
                            'Content-Type' : 'application/json'
                        },
                        params: jsonData,
                        success : function(response){
                            win.close();
                            var responseText = Ext.JSON.decode(response.responseText);
                            if(responseText.success){
                                var userListStore = Ext.data.StoreManager.lookup('DepartmentListViewStore');
                                userListStore.removeAll();
                                userListStore.load();
                            }
                            else{
                                Ext.Msg.show({
                                    title: '添加部门失败',
                                    msg : responseText.message,
                                    buttions: Ext.Msg.OK,
                                    icon: Ext.Msg.ERROR
                                });
                            }

                        },
                        failure: function(form, action){

                            if (action.failureType === Ext.form.action.Action.CLIENT_INVALID) {

                                Ext.Msg.show({
                                    title:'失败',
                                    msg: '填写的信息不合规范',
                                    buttons: Ext.Msg.OK,
                                    icon: Ext.Msg.ERROR
                                });

                            }

                            if (action.failureType === Ext.form.action.Action.CONNECT_FAILURE){

                                Ext.Msg.show({
                                    title:'失败',
                                    msg: '状态:'+action.response.status+': '+action.response.statusText,
                                    buttons: Ext.Msg.OK,
                                    icon: Ext.Msg.ERROR
                                });

                            }

                            if (action.failureType === Ext.form.action.Action.SERVER_INVALID){

                                // server responded with success = false
                                Ext.Msg.show({
                                    title:'失败',
                                    msg: action.result.errormsg,
                                    buttons: Ext.Msg.OK,
                                    icon: Ext.Msg.ERROR
                                });

                            }

                        }


                    });

        }
    },

    onAddDepResetClick: function(button, e, eOpts) {
        var win = button.up('window');
                        var form = win.down('form').getForm();
        form.reset();
    },

    validateDepName: function(value) {
        if(value.length >= 1){
        Ext.Ajax.setTimeout(20000);
                    Ext.Ajax.request({
                        url:'admin/depNameValidate.action',
                        method: 'GET',
                        async: false,
                        params :{
                            depName : value
                        },
                        success: function(response){
                            var respText = Ext.JSON.decode(response.responseText);
                            if(respText.success){
                                Ext.getCmp('departmentDesc').focus();
                                Ext.Msg.alert('提示','部门名可用');
                            }

                            else{
                                Ext.getCmp('username').focus();
                                Ext.Msg.alert('提示',value + '已经存在');
                            }


                        },
                        failure: function(form,action){

                            Ext.getCmp('departmentName').focus();
                            Ext.Msg.alert('提示','验证部门名出错');

                        }

                    });


                }

    }

});