/*
 * File: app/view/AddUser.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Xixixi.view.AddUser', {
    extend: 'Ext.window.Window',
    alias: 'widget.adduser',

    requires: [
        'Xixixi.view.AddUserViewModel',
        'Ext.form.Panel',
        'Ext.form.field.Text'
    ],

    viewModel: {
        type: 'adduser'
    },
    autoShow: true,
    height: 475,
    hidden: false,
    id: 'addUserWindow',
    minHeight: 450,
    resizable: false,
    width: 560,
    title: '添加用户',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'form',
            flex: 1,
            id: 'addUserForm',
            itemId: 'addUserForm',
            margin: '10 10 10 10',
            bodyPadding: 10,
            bodyStyle: 'background:#DFE8F6;\r\nborder:1px solid #B5B8C8',
            header: false,
            title: 'My Form',
            items: [
                {
                    xtype: 'textfield',
                    validator: function(value) {
                        if(value.length >= 3){
                            var result = this.validateUserName(value);
                            return result;
                        }
                    },
                    validateUserName: function(value) {
                        Ext.Ajax.setTimeout(20000);
                        Ext.Ajax.request({
                            url:'admin/userIdValidate.action',
                            method: 'GET',
                            async: false,
                            params :{
                                userName : value
                            },
                            success: function(response){
                                var respText = Ext.Json.Decode(response.responseText);
                                if(respText.success)
                                result = true;
                                else
                                result = value + "已经存在！";

                            },
                            failure: function(form,action){
                                result = "验证用户名出错";
                            }

                        });
                        console.log(value);
                        return result;
                    },
                    anchor: '100%',
                    maxWidth: 500,
                    width: 300,
                    fieldLabel: '用户名',
                    labelAlign: 'right',
                    labelPad: 10,
                    labelWidth: 120,
                    name: 'userName',
                    allowBlank: false,
                    regex: /^[a-z0-9_]{3,15}$/,
                    regexText: '用户名必须由3-15个大小写字母，数字或下划线组成'
                }
            ]
        }
    ]

});