/*
 * File: app/view/AdminViewportViewModel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Xixixi.view.AdminViewportViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.adminviewport',

    requires: [
        'Ext.data.Store',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json',
        'Ext.data.writer.Json'
    ],

    stores: {
        userListViewStore: {
            autoLoad: true,
            model: 'Xixixi.model.UserListModel',
            proxy: {
                type: 'ajax',
                url: 'admin/userLoad.action',
                reader: {
                    type: 'json',
                    rootProperty: 'results'
                },
                writer: {
                    type: 'json',
                    rootProperty: 'data'
                }
            }
        },
        departmentListViewStore: {
            autoLoad: true,
            model: 'Xixixi.model.DepartmentListModel',
            proxy: {
                type: 'ajax',
                url: 'admin/departmentLoad.action',
                reader: {
                    type: 'json',
                    rootProperty: 'results'
                },
                writer: {
                    type: 'json',
                    rootProperty: 'data'
                }
            }
        }
    }

});