/*
 * File: app/model/LaundryOrder.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Xixixi.model.LaundryOrder', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Date'
    ],

    fields: [
        {
            name: 'orderId'
        },
        {
            name: 'orderBy'
        },
        {
            name: 'csRep'
        },
        {
            name: 'pickedUpBy'
        },
        {
            name: 'deliveredBy'
        },
        {
            name: 'price'
        },
        {
            name: 'actualIncome'
        },
        {
            name: 'orderStatus'
        },
        {
            type: 'date',
            name: 'lastUpdateTime',
            dateFormat: 'time'
        },
        {
            name: 'lastUpdatedBy'
        },
        {
            name: 'comments'
        },
        {
            type: 'date',
            name: 'preferedPickupStime'
        },
        {
            type: 'date',
            name: 'preferedPickupEtime'
        }
    ],

    hasMany: {
        model: 'Xixixi.model.OrderItem',
        name: 'orderItems',
        associationKey: 'order_Items'
    },

    hasOne: {
        model: 'Xixixi.model.Address',
        name: 'address'
    }
});