/*
 * File: app/model/UserListModel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Xixixi.model.UserListModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.String',
        'Ext.data.field.Date'
    ],

    fields: [
        {
            type: 'string',
            name: 'userName'
        },
        {
            type: 'string',
            name: 'department'
        },
        {
            type: 'string',
            name: 'role'
        },
        {
            type: 'string',
            name: 'manager'
        },
        {
            type: 'string',
            name: 'fullName'
        },
        {
            type: 'date',
            name: 'createdDate'
        }
    ]
});