/*
 * File: app/view/ContactCustomer.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Xixixi.view.ContactCustomer', {
    extend: 'Ext.window.Window',
    alias: 'widget.contactcustomer',

    requires: [
        'Xixixi.view.ContactCustomerViewModel',
        'Ext.form.Panel',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.view.Table',
        'Ext.form.field.Date',
        'Ext.form.field.Time',
        'Ext.form.field.TextArea',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'contactcustomer'
    },
    height: 640,
    hidden: false,
    width: 500,
    title: '联系客户',
    defaultListenerScope: true,

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'form',
            flex: 1,
            bodyPadding: 10,
            header: false,
            title: 'My Form',
            items: [
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    hidden: true,
                    fieldLabel: '订单号',
                    name: 'orderId'
                },
                {
                    xtype: 'container',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            padding: '10 0 10 0',
                            fieldLabel: '下单客户',
                            labelWidth: 60,
                            name: 'orderBy',
                            editable: false
                        },
                        {
                            xtype: 'textfield',
                            padding: '10 0 10 0',
                            fieldLabel: '下单时间',
                            labelWidth: 60,
                            name: 'createDate',
                            editable: false
                        }
                    ]
                },
                {
                    xtype: 'container',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            padding: '10 0 10 0',
                            fieldLabel: '姓名',
                            labelWidth: 60,
                            name: 'fullName'
                        },
                        {
                            xtype: 'textfield',
                            padding: '10 0 10 0',
                            fieldLabel: '联系方式',
                            labelWidth: 60,
                            name: 'phoneNumber'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    width: 150,
                    layout: 'table',
                    items: [
                        {
                            xtype: 'textfield',
                            padding: '10 10 10 0',
                            width: 150,
                            fieldLabel: '省份',
                            labelWidth: 40,
                            name: 'state'
                        },
                        {
                            xtype: 'textfield',
                            maxWidth: 150,
                            padding: '10 10 10 0',
                            width: 150,
                            fieldLabel: '城市',
                            labelWidth: 40,
                            name: 'city'
                        },
                        {
                            xtype: 'textfield',
                            maxWidth: 150,
                            padding: '10 0 10 0',
                            width: 150,
                            fieldLabel: '小区',
                            labelWidth: 40,
                            name: 'district'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            maxWidth: 220,
                            padding: '10 0 10 0',
                            width: 220,
                            fieldLabel: '街道',
                            labelWidth: 40,
                            name: 'street'
                        },
                        {
                            xtype: 'textfield',
                            maxWidth: 250,
                            padding: '10 0 10 0',
                            width: 280,
                            fieldLabel: '门牌号',
                            labelWidth: 50,
                            name: 'streetNum'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    height: 180,
                    items: [
                        {
                            xtype: 'gridpanel',
                            width: 470,
                            title: '订单',
                            store: 'RecordOrderItemStore',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    width: 80,
                                    dataIndex: 'itemName',
                                    text: '类别'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'itemName',
                                    text: '物品'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    width: 90,
                                    dataIndex: 'amount',
                                    text: '数量'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'pricePerItem',
                                    text: '单价'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'totalPrice',
                                    text: '总价'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    padding: '10 0 10 0',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'datefield',
                            fieldLabel: '取单最早日期',
                            name: 'preferedPickupSDate',
                            allowBlank: false,
                            submitFormat: 'm/d/Y'
                        },
                        {
                            xtype: 'timefield',
                            flex: 1,
                            margin: '0 10',
                            fieldLabel: '时间',
                            labelWidth: 50,
                            name: 'preferedPickupSTime',
                            allowBlank: false,
                            format: 'g:i a',
                            increment: 60,
                            maxValue: '8:00 PM',
                            minValue: '8:00 AM',
                            submitFormat: 'H:i'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    padding: '10 0 10 0',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'datefield',
                            fieldLabel: '取单最晚日期',
                            name: 'preferedPickupEDate',
                            allowBlank: false,
                            submitFormat: 'm/d/Y'
                        },
                        {
                            xtype: 'timefield',
                            flex: 1,
                            margin: '0 10',
                            fieldLabel: '时间',
                            labelWidth: 50,
                            name: 'preferedPickupETime',
                            allowBlank: false,
                            increment: 60,
                            format: 'g:i a',
                            maxValue: '8:00 PM',
                            minValue: '8:00 AM',
                            submitFormat: 'H:i'
                        }
                    ]
                },
                {
                    xtype: 'textareafield',
                    scrollable: false,
                    width: 470,
                    fieldLabel: '备注',
                    name: 'comments'
                },
                {
                    xtype: 'container',
                    margin: '20 20 20 20',
                    layout: {
                        type: 'hbox',
                        align: 'stretch',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'button',
                            margin: '15 40 15 0',
                            width: 50,
                            text: '完成',
                            listeners: {
                                click: 'onButtonClick'
                            }
                        },
                        {
                            xtype: 'button',
                            margin: '15 0 15 50',
                            text: '取消',
                            listeners: {
                                click: 'onButtonClick1'
                            }
                        }
                    ]
                }
            ]
        }
    ],

    onButtonClick: function(button, e, eOpts) {


        						var win = button.up('window');
        						var form = win.down('form').getForm();
        						if (form.isValid()) {

        							var jsonData = Ext.JSON.encode(form.getValues());
        							Ext.Ajax.setTimeout(40000);
        							Ext.Ajax.request({
        										url : 'contactCustomer.action',
        										method : 'POST',
        										headers : {
        											'Content-Type' : 'application/json'
        										},
        										params : jsonData,
        										success : function(response) {
        											win.close();
        											var responseText = Ext.JSON
        													.decode(response.responseText);
        											if (responseText.success) {
        												var orderListStore = Ext.data.StoreManager
        														.lookup('OrderListStore');
        												orderListStore.removeAll();
        												orderListStore.getProxy().extraParams = {
        													orderStatus : 1
        												};
        												orderListStore.load();
        											} else {
        												if (Ext.MessageBox) {
        													Ext.MessageBox.buttonText = {
        														ok : "确定",
        														cancel : "取消",
        														yes : "是",
        														no : "否"
        													};
        												}
        												Ext.Msg.show({
        													title : '服务器失败',
        													msg : responseText.message,
        													buttions : Ext.Msg.OK,
        													icon : Ext.Msg.ERROR
        												});
        											}

        										},
        										failure : function(form, action) {
        											if (Ext.MessageBox) {
        												Ext.MessageBox.buttonText = {
        													ok : "确定",
        													cancel : "取消",
        													yes : "是",
        													no : "否"
        												};
        											}

        											if (action.failureType === Ext.form.action.Action.CLIENT_INVALID) {

        												Ext.Msg.show({
        													title : '失败',
        													msg : '填写的信息不合规范',
        													buttons : Ext.Msg.OK,
        													icon : Ext.Msg.ERROR
        												});

        											}

        											if (action.failureType === Ext.form.action.Action.CONNECT_FAILURE) {

        												Ext.Msg
        														.show({
        															title : '失败',
        															msg : '状态:'+ action.response.status+ ': '+ action.response.statusText,
        															buttons : Ext.Msg.OK,
        															icon : Ext.Msg.ERROR
        														});

        											}

        											if (action.failureType === Ext.form.action.Action.SERVER_INVALID) {

        												// server responded with success = false
        												Ext.Msg
        														.show({
        															title : '失败',
        															msg : action.result.errormsg,
        															buttons : Ext.Msg.OK,
        															icon : Ext.Msg.ERROR
        														});

        											}

        										}

        									});

        						}


    },

    onButtonClick1: function(button, e, eOpts) {
        var win = button.up('window');
        var form = win.down('form').getForm();
        form.reset();
        win.close();
    }

});