/*
 * File: app/view/ContactCustomer.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Xixixi.view.ContactCustomer', {
    extend: 'Ext.window.Window',
    alias: 'widget.contactcustomer',

    requires: [
        'Xixixi.view.ContactCustomerViewModel',
        'Ext.form.Panel',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.view.Table',
        'Ext.form.field.Date',
        'Ext.form.field.Time',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'contactcustomer'
    },
    height: 600,
    hidden: false,
    width: 500,
    title: '联系客户',
    defaultListenerScope: true,

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'form',
            flex: 1,
            bodyPadding: 10,
            header: false,
            title: 'My Form',
            items: [
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    hidden: true,
                    fieldLabel: '订单号',
                    name: 'orderId'
                },
                {
                    xtype: 'container',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            padding: '10 0 10 0',
                            fieldLabel: '下单客户',
                            labelWidth: 60,
                            name: 'orderBy',
                            editable: false
                        },
                        {
                            xtype: 'textfield',
                            padding: '10 0 10 0',
                            fieldLabel: '下单时间',
                            labelWidth: 60,
                            name: 'createDate',
                            editable: false
                        }
                    ]
                },
                {
                    xtype: 'container',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            padding: '10 0 10 0',
                            fieldLabel: '姓名',
                            labelWidth: 60,
                            name: 'fullName'
                        },
                        {
                            xtype: 'textfield',
                            padding: '10 0 10 0',
                            fieldLabel: '联系方式',
                            labelWidth: 60,
                            name: 'phoneNumber'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    width: 150,
                    layout: 'table',
                    items: [
                        {
                            xtype: 'textfield',
                            padding: '10 10 10 0',
                            width: 150,
                            fieldLabel: '省份',
                            labelWidth: 40,
                            name: 'state'
                        },
                        {
                            xtype: 'textfield',
                            maxWidth: 150,
                            padding: '10 10 10 0',
                            width: 150,
                            fieldLabel: '城市',
                            labelWidth: 40,
                            name: 'city'
                        },
                        {
                            xtype: 'textfield',
                            maxWidth: 150,
                            padding: '10 0 10 0',
                            width: 150,
                            fieldLabel: '小区',
                            labelWidth: 40,
                            name: 'district'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            maxWidth: 220,
                            padding: '10 0 10 0',
                            width: 220,
                            fieldLabel: '街道',
                            labelWidth: 40,
                            name: 'street'
                        },
                        {
                            xtype: 'textfield',
                            maxWidth: 250,
                            padding: '10 0 10 0',
                            width: 280,
                            fieldLabel: '门牌号',
                            labelWidth: 50,
                            name: 'streetNum'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    height: 200,
                    items: [
                        {
                            xtype: 'gridpanel',
                            width: 470,
                            title: '订单',
                            store: 'RecordOrderItemStore',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    width: 80,
                                    dataIndex: 'itemName',
                                    text: '类别'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'itemName',
                                    text: '物品'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    width: 90,
                                    dataIndex: 'amount',
                                    text: '数量'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'pricePerItem',
                                    text: '单价'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'totalPrice',
                                    text: '总价'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    padding: '10 0 10 0',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'datefield',
                            fieldLabel: '取单最早日期',
                            name: 'preferedPickupSDate'
                        },
                        {
                            xtype: 'timefield',
                            flex: 1,
                            margin: '0 10',
                            fieldLabel: '时间',
                            labelWidth: 50,
                            name: 'preferedPickupSTime',
                            maxValue: '8:00 PM',
                            minValue: '8:00 AM'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    padding: '10 0 10 0',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'datefield',
                            fieldLabel: '取单最晚日期',
                            name: 'preferedPickupEDate'
                        },
                        {
                            xtype: 'timefield',
                            flex: 1,
                            margin: '0 10',
                            fieldLabel: '时间',
                            labelWidth: 50,
                            name: 'preferedPickupETime',
                            maxValue: '8:00 PM',
                            minValue: '8:00 AM'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    margin: '20 20 20 20',
                    layout: {
                        type: 'hbox',
                        align: 'stretch',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'button',
                            margin: '15 40 15 0',
                            width: 50,
                            text: '完成',
                            listeners: {
                                click: 'onButtonClick'
                            }
                        },
                        {
                            xtype: 'button',
                            margin: '15 0 15 50',
                            text: '取消',
                            listeners: {
                                click: 'onButtonClick1'
                            }
                        }
                    ]
                }
            ]
        }
    ],

    onButtonClick: function(button, e, eOpts) {
    	
    	var win = button.up('window');
        var form = win.down('form').getForm();
        if(form.isValid()){
        var jsonData = Ext.JSON.encode(form.getValues());
        console.log(jsonData);
      }
       
    },

    onButtonClick1: function(button, e, eOpts) {
    	 var win = button.up('window');
         var form = win.down('form').getForm();
         form.reset();
         win.close();
    }

});