/*
 * File: app/view/OrderMainViewport.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Xixixi.view.OrderMainViewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.ordermainviewport',

    requires: [
        'Xixixi.view.OrderMainViewportViewModel',
        'Xixixi.view.OrderMainViewportViewController',
        'Ext.XTemplate',
        'Ext.Img',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Action',
        'Ext.grid.plugin.RowExpander',
        'Ext.toolbar.Paging',
        'Ext.form.Panel',
        'Ext.grid.feature.Summary',
        'Ext.grid.column.Number',
        'Ext.form.field.Number',
        'Ext.grid.plugin.CellEditing',
        'Ext.grid.feature.Grouping',
        'Ext.form.field.TextArea',
        'Ext.form.field.Date',
        'Ext.form.field.Time',
        'Ext.button.Button',
        'Xixixi.view.ContactCustomer'
    ],

    controller: 'ordermainviewport',
    viewModel: {
        type: 'ordermainviewport'
    },
    padding: '',
    style: 'background-color: #EFEFEF;',
    layout: 'border',

    items: [
        {
            xtype: 'container',
            region: 'north',
            height: 150,
            id: 'header',
            maxHeight: 97
        },
        {
            xtype: 'toolbar',
            region: 'north',
            height: 38,
            id: 'breadcrumbs',
            items: [
                {
                    xtype: 'container',
                    height: 38,
                    html: '<span class="pageAnchorTitle">订单管理</span>',
                    padding: '11 10 0 15'
                },
                {
                    xtype: 'container',
                    flex: 1
                },
                {
                    xtype: 'dataview',
                    height: 38,
                    padding: '5 10 0 0',
                    tpl: [
                        '<tpl for=".">',
                        '    <div class=".pageAnchorTitle">欢迎 {username}</div>',
                        '     </tpl>'
                    ],
                    itemSelector: '.pageAnchorTitle',
                    store: 'GetUserNameStore'
                },
                {
                    xtype: 'container',
                    height: 38,
                    html: '|'
                },
                {
                    xtype: 'container',
                    height: 38,
                    html: '<A class="pageAnchor" href="j_spring_security_logout"> Logout </A>',
                    padding: '11 10 0 0'
                }
            ]
        },
        {
            xtype: 'panel',
            region: 'west',
            padding: '',
            width: 150,
            bodyStyle: 'background-color: #EFEFEF;',
            collapsible: true,
            title: '导航',
            titleAlign: 'right',
            items: [
                {
                    xtype: 'container',
                    html: '<div class="menu_operator">待处理订单</div>',
                    id: 'menu_orderwaiting'
                },
                {
                    xtype: 'container',
                    html: '<div class="menu_operator">等待取货订单</div>',
                    id: 'menu_processed'
                },
                {
                    xtype: 'container',
                    html: '<div class="menu_operator">已取消订单</div>',
                    id: 'menu_canceled'
                },
                {
                    xtype: 'container',
                    html: '<div class="menu_operator">替客户下单</div>',
                    id: 'menu_createorder'
                }
            ]
        },
        {
            xtype: 'container',
            region: 'center',
            scrollable: true,
            items: [
                {
                    xtype: 'panel',
                    height: 90,
                    padding: 5,
                    collapsed: false,
                    collapsible: true,
                    title: '查找订单',
                    titleAlign: 'right',
                    titleCollapse: true,
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 1,
                            reference: 'searchContainerRef',
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    itemId: 'cellPhoneField',
                                    padding: '10 10 10 10',
                                    fieldLabel: '下单手机/座机号',
                                    name: 'cellPhone'
                                },
                                {
                                    xtype: 'textfield',
                                    itemId: 'orderIdField',
                                    padding: '10 10 10 10',
                                    width: 300,
                                    fieldLabel: '订单号',
                                    labelWidth: 45,
                                    name: 'orderId'
                                },
                                {
                                    xtype: 'image',
                                    flex: 1,
                                    id: 'searchIcon',
                                    margin: '10 10 10 10 ',
                                    maxWidth: 25,
                                    width: '',
                                    src: 'orderPage/images/find.png'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    reference: 'orderCenterContainerRef',
                    id: 'orderCenterContainer',
                    itemId: 'orderCenterContainer',
                    layout: 'card',
                    items: [
                        {
                            xtype: 'gridpanel',
                            reference: 'waitingOrderGridRef',
                            height: 600,
                            id: 'waitingOrderGrid',
                            padding: 5,
                            width: 300,
                            collapsible: false,
                            reserveScrollbar: true,
                            store: 'OrderListStore',
                            columns: [
                                {
                                    xtype: 'actioncolumn',
                                    align: 'center',
                                    text: '联系客户',
                                    items: [
                                        {
                                            handler: function(view, rowIndex, colIndex, item, e, record, row) {


                                                var contactWindow = Ext.create('Xixixi.view.ContactCustomer');
                                                contactWindow.show();
                                                var form = contactWindow.down('form').getForm();
                                                var recorddata = record.data;
                                                var address = recorddata.address;
                                                var cd = Ext.Date.format(recorddata.createDate,'Y-m-d H:i:s');
                                                var pst = recorddata.preferedPickupStime;
                                                var pet = recorddata.preferedPickupEtime;
                                                var parsePst = Ext.Date.format(pst,'g:i A');
                                                var parsePet = Ext.Date.format(pet,'g:i A');

                                                form.setValues({
                                                    orderId : recorddata.orderId,
                                                    orderBy : recorddata.orderBy,
                                                    comments : recorddata.comments,
                                                    createDate  : cd,
                                                    preferedPickupSDate: pst,
                                                    preferedPickupEDate: pet,
                                                    preferedPickupSTime: parsePst,
                                                    preferedPickupETime : parsePet,
                                                    fullName : address.fullName,
                                                    phoneNumber : address.phoneNum,
                                                    state : address.state,
                                                    city : address.city,
                                                    district : address.district,
                                                    street : address.street,
                                                    streetNum : address.streetNum

                                                });
                                                var gridStore = Ext.data.StoreManager.lookup('RecordOrderItemStore');
                                                gridStore.removeAll();
                                                gridStore.loadData(recorddata.orderItems);



                                            },
                                            icon: 'orderPage/images/customer.png',
                                            tooltip: '联系客户'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'actioncolumn',
                                    width: '',
                                    align: 'center',
                                    text: '取消订单',
                                    items: [
                                        {
                                            handler: function(view, rowIndex, colIndex, item, e, record, row) {

                                                var oId = record.data.orderId;
                                                if (Ext.MessageBox) {
                                                    Ext.MessageBox.buttonText = {
                                                        ok : "确定",
                                                        cancel : "取消",
                                                        yes : "是",
                                                        no : "否"
                                                    };
                                                }
                                                Ext.MessageBox.confirm('取消订单','确定取消订单号为'+oId+'的订单',
                                                function(e){
                                                    if(e=='yes'){
                                                        Ext.Ajax.timeout = 40000;
                                                        Ext.Ajax.request({
                                                            url : 'cancelOrder.action',
                                                            method : 'POST',
                                                            params :{
                                                                orderId : oId
                                                            },
                                                            success: function(response){
                                                                var respText = Ext.JSON.decode(response.responseText);
                                                                if(respText.success){
                                                                    Ext.Msg.alert('成功',respText.message);

                                                                    var store = Ext.data.StoreManager.lookup('OrderListStore');
                                                                    store.removeAll();
                                                                    store.getProxy().extraParams = {orderStatus : 1};
                                                                    store.load();
                                                                }else{
                                                                    Ext.Msg.alert('失败',respText.message);
                                                                }
                                                            },
                                                            failure : function(response){
                                                                Ext.Msg.alert('失败','网络可能有问题');
                                                            }
                                                        });

                                                    }
                                                }

                                                );


                                            },
                                            icon: 'orderPage/images/error.png',
                                            tooltip: '取消订单'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'orderId',
                                    text: '订单号'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'orderBy',
                                    text: '下单客户'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'createDate',
                                    formatter: 'date("Y-m-d H:i:s")',
                                    text: '下单时间'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'csRep',
                                    text: '联系客服'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'pickedUpBy',
                                    text: '取单快递'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'deliveredBy',
                                    text: '送单快递'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'price',
                                    text: '总价'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'actualIncome',
                                    text: '实收'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'orderStatus',
                                    text: '订单状态'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'lastUpdatedBy',
                                    text: '最后更新'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'lastUpdateTime',
                                    formatter: 'date("Y-m-d H:i:s")',
                                    text: '最后更新时间'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'comments',
                                    text: '备注'
                                }
                            ],
                            plugins: [
                                {
                                    ptype: 'rowexpander',
                                    rowBodyTpl: [
                                        '<div>地址: {address.state} {address.city} {address.district} {address.street} {address.streetNum} {address.zipcode}</div>',
                                        '<div>联系方式: {address.fullName} {address.phoneNumber}</div>',
                                        '<div>类别: <tpl for="orderItems"> {itemName} : {amount}件,单项总价:{totalPrice}</tpl></div>'
                                    ]
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'pagingtoolbar',
                                    dock: 'bottom',
                                    width: 360,
                                    afterPageText: '页，共 {0}页',
                                    beforePageText: '第',
                                    displayInfo: true,
                                    displayMsg: '展示 {2}条中的{0} - {1} ',
                                    emptyMsg: '没有记录',
                                    firstText: '第一页',
                                    lastText: '最后一页',
                                    nextText: '下一页',
                                    prevText: '上一页',
                                    refreshText: '刷新',
                                    store: 'OrderListStore'
                                }
                            ]
                        },
                        {
                            xtype: 'gridpanel',
                            reference: 'processedOrderGridRef',
                            height: 600,
                            id: 'processedOrderGrid',
                            padding: 5,
                            scrollable: true,
                            width: 300,
                            collapsible: false,
                            store: 'OrderListStore',
                            columns: [
                                {
                                    xtype: 'actioncolumn',
                                    hidden: true,
                                    width: '',
                                    align: 'center',
                                    text: '取消订单',
                                    items: [
                                        {
                                            handler: function(view, rowIndex, colIndex, item, e, record, row) {

                                            },
                                            icon: 'orderPage/images/error.png',
                                            tooltip: '取消订单'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'orderId',
                                    text: '订单号'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'orderBy',
                                    text: '下单客户'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'createDate',
                                    formatter: 'date("Y-m-d H:i:s")',
                                    text: '下单时间'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'csRep',
                                    text: '联系客服'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'pickedUpBy',
                                    text: '取单快递'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'deliveredBy',
                                    text: '送单快递'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'price',
                                    text: '总价'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'actualIncome',
                                    text: '实收'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'orderStatus',
                                    text: '订单状态'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'lastUpdatedBy',
                                    text: '最后更新'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'lastUpdateTime',
                                    formatter: 'date("Y-m-d H:i:s")',
                                    text: '最后更新时间'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'comments',
                                    text: '备注'
                                }
                            ],
                            plugins: [
                                {
                                    ptype: 'rowexpander',
                                    rowBodyTpl: [
                                        '<div>地址: {address.state} {address.city} {address.district} {address.street} {address.streetNum} {address.zipcode}</div>',
                                        '<div>联系方式: {address.fullName} {address.phoneNumber}</div>',
                                        '<div>类别: <tpl for="orderItems"> {itemName} : {amount}件,单项总价:{totalPrice}</tpl></div>'
                                    ]
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'pagingtoolbar',
                                    dock: 'bottom',
                                    width: 360,
                                    afterPageText: '页，共 {0}页',
                                    beforePageText: '第',
                                    displayInfo: true,
                                    displayMsg: '展示 {2}条中的{0} - {1} ',
                                    emptyMsg: '没有记录',
                                    firstText: '第一页',
                                    lastText: '最后一页',
                                    nextText: '下一页',
                                    prevText: '上一页',
                                    refreshText: '刷新',
                                    store: 'OrderListStore'
                                }
                            ]
                        },
                        {
                            xtype: 'gridpanel',
                            reference: 'canceledOrderGridRef',
                            height: 600,
                            id: 'canceledOrderGrid',
                            padding: 5,
                            scrollable: true,
                            width: 300,
                            collapsible: false,
                            store: 'OrderListStore',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'orderId',
                                    text: '订单号'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'orderBy',
                                    text: '下单客户'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'createDate',
                                    formatter: 'date("Y-m-d H:i:s")',
                                    text: '下单时间'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'csRep',
                                    text: '联系客服'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'pickedUpBy',
                                    text: '取单快递'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'deliveredBy',
                                    text: '送单快递'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'price',
                                    text: '总价'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'actualIncome',
                                    text: '实收'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'orderStatus',
                                    text: '订单状态'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'lastUpdatedBy',
                                    text: '最后更新'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'lastUpdateTime',
                                    formatter: 'date("Y-m-d H:i:s")',
                                    text: '最后更新时间'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'comments',
                                    text: '备注'
                                }
                            ],
                            plugins: [
                                {
                                    ptype: 'rowexpander',
                                    rowBodyTpl: [
                                        '<div>地址: {address.state} {address.city} {address.district} {address.street} {address.streetNum} {address.zipcode}</div>',
                                        '<div>联系方式: {address.fullName} {address.phoneNumber}</div>',
                                        '<div>类别: <tpl for="orderItems"> {itemName} : {amount}件,单项总价:{totalPrice}</tpl></div>'
                                    ]
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'pagingtoolbar',
                                    dock: 'bottom',
                                    width: 360,
                                    afterPageText: '页，共 {0}页',
                                    beforePageText: '第',
                                    displayInfo: true,
                                    displayMsg: '展示 {2}条中的{0} - {1} ',
                                    emptyMsg: '没有记录',
                                    firstText: '第一页',
                                    lastText: '最后一页',
                                    nextText: '下一页',
                                    prevText: '上一页',
                                    refreshText: '刷新',
                                    store: 'OrderListStore'
                                }
                            ]
                        },
                        {
                            xtype: 'form',
                            height: 600,
                            bodyPadding: 10,
                            header: false,
                            title: 'My Form',
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    height: 400,
                                    width: '50%',
                                    items: [
                                        {
                                            xtype: 'gridpanel',
                                            padding: '80 20 0 0',
                                            title: '订单',
                                            store: 'CategoryPriceStore',
                                            features: [
                                                {
                                                    ftype: 'summary',
                                                    dock: 'top'
                                                },
                                                {
                                                    ftype: 'grouping'
                                                }
                                            ],
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'category',
                                                    text: '类别'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'itemName',
                                                    text: '名称'
                                                },
                                                {
                                                    xtype: 'numbercolumn',
                                                    dataIndex: 'amount',
                                                    text: '数量',
                                                    format: '0,000',
                                                    editor: {
                                                        xtype: 'numberfield',
                                                        maxValue: 500,
                                                        minValue: 0
                                                    }
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'unitPrice',
                                                    text: '单价'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                                        var amount = record.get('amount');
                                                        var unitPrice = record.get('unitPrice');
                                                        return amount*unitPrice;
                                                    },
                                                    summaryRenderer: function(val, params, data) {
                                                        return '总计' +val+'元';
                                                    },
                                                    summaryType: 'sum',
                                                    dataIndex: 'totalPrice',
                                                    text: '单项总价'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    hidden: true,
                                                    dataIndex: 'categoryId',
                                                    text: 'CategoryId'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    hidden: true,
                                                    dataIndex: 'itemId',
                                                    text: 'ItemId'
                                                }
                                            ],
                                            plugins: [
                                                {
                                                    ptype: 'cellediting',
                                                    clicksToEdit: 1
                                                }
                                            ],
                                            listeners: {
                                                edit: 'onGridpanelEdit'
                                            }
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    padding: '80 70',
                                    width: '50%',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: '下单客户(手机)',
                                            name: 'orderBy'
                                        },
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: '姓名',
                                            name: 'fullName',
                                            allowBlank: false,
                                            allowOnlyWhitespace: false
                                        },
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: '联系方式',
                                            name: 'phoneNumber',
                                            allowBlank: false,
                                            allowOnlyWhitespace: false
                                        },
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: '省份',
                                            name: 'state'
                                        },
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: '城市',
                                            name: 'city'
                                        },
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: '小区',
                                            name: 'district',
                                            allowBlank: false,
                                            allowOnlyWhitespace: false
                                        },
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: '街道',
                                            name: 'street',
                                            allowBlank: false,
                                            allowOnlyWhitespace: false
                                        },
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: '门牌号',
                                            name: 'streetNum',
                                            allowBlank: false,
                                            allowOnlyWhitespace: false
                                        },
                                        {
                                            xtype: 'textareafield',
                                            fieldLabel: '备注',
                                            name: 'comments'
                                        },
                                        {
                                            xtype: 'datefield',
                                            fieldLabel: '最早取单日期',
                                            name: 'preferedPickupSDate',
                                            allowBlank: false,
                                            allowOnlyWhitespace: false,
                                            blankText: '必填项',
                                            submitFormat: 'm/d/Y'
                                        },
                                        {
                                            xtype: 'timefield',
                                            fieldLabel: '最早时间',
                                            name: 'preferedPickupSTime',
                                            allowBlank: false,
                                            blankText: '必填项',
                                            format: 'g:i a',
                                            increment: 60,
                                            maxValue: '9:00 PM',
                                            minValue: '9:00 AM',
                                            submitFormat: 'H:i'
                                        },
                                        {
                                            xtype: 'datefield',
                                            fieldLabel: '最晚取单日期',
                                            name: 'preferedPickupEDate',
                                            allowBlank: false,
                                            allowOnlyWhitespace: false,
                                            blankText: '必填项',
                                            submitFormat: 'm/d/Y'
                                        },
                                        {
                                            xtype: 'timefield',
                                            fieldLabel: '最晚时间',
                                            name: 'preferedPickupETime',
                                            allowBlank: false,
                                            blankText: '必填项',
                                            format: 'h:i',
                                            increment: 60,
                                            maxValue: '9:00 AM',
                                            minValue: '9:00 PM',
                                            submitFormat: 'H:i'
                                        },
                                        {
                                            xtype: 'button',
                                            margin: '20 120',
                                            text: '提交',
                                            listeners: {
                                                click: 'onButtonClick'
                                            }
                                        }
                                    ]
                                }
                            ]
                        }
                    ],
                    listeners: {
                        _afterrender0: 'onOrderCenterContainerAfterRender',
                        _afterrender1: 'onOrderCenterContainerAfterRender1',
                        _afterrender2: 'onOrderCenterContainerAfterRender2',
                        _afterrender3: 'onOrderCenterContainerAfterRender3',
                        _afterrender4: 'onOrderCenterContainerAfterRender4',
                        afterrender: function() {
                            var me = this,
                                args = Ext.toArray(arguments, 0, -1);
                            args.unshift('_afterrender0');
                            me.fireEvent.apply(me, args);
                            args[0] = '_afterrender1';
                            me.fireEvent.apply(me, args);
                            args[0] = '_afterrender2';
                            me.fireEvent.apply(me, args);
                            args[0] = '_afterrender3';
                            me.fireEvent.apply(me, args);
                            args[0] = '_afterrender4';
                            me.fireEvent.apply(me, args);
                        }
                    }
                }
            ]
        }
    ]

});