/*
 * File: app/view/OrderMainViewportViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Xixixi.view.OrderMainViewportViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.ordermainviewport',

    onOrderCenterContainerAfterRender: function(component, eOpts) {

        Ext.get('menu_orderwaiting').on('click',function(){
            var grid = this.lookupReference('waitingOrderGridRef');
            var store = grid.store;
            store.removeAll();
            store.getProxy().extraParams = {orderStatus : 1,page : 1,
            limit : 25};
            store.load();

        },this);
    },

    onOrderCenterContainerAfterRender1: function(component, eOpts) {
        Ext.get('menu_processed').on('click',function(){
            var grid = this.lookupReference('processedOrderGridRef');
            var store = grid.store;
            store.removeAll();
            store.getProxy().extraParams = {orderStatus : 2,page : 1,
            limit : 25};
            store.load();

        },this);
    },

    onOrderCenterContainerAfterRender2: function(component, eOpts) {
        Ext.get('menu_canceled').on('click',function(){
            var grid = this.lookupReference('canceledOrderGridRef');
            var store = grid.store;
            store.removeAll();
            store.getProxy().extraParams = {orderStatus : 3,page : 1,
            limit : 25};
            store.load();

        },this);
    }

});
