/*
 * File: app/store/UserListStore.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Xixixi.store.UserListStore', {
    extend: 'Ext.data.Store',

    requires: [
        'Xixixi.model.UserListModel',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json',
        'Ext.data.writer.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'UserListStore',
            model: 'Xixixi.model.UserListModel',
            proxy: {
                type: 'ajax',
                url: 'admin/userLoad.action',
                reader: {
                    type: 'json',
                    rootProperty: 'results'
                },
                writer: {
                    type: 'json',
                    rootProperty: 'data'
                },
                listeners: {
                    exception: {
                        fn: me.onAjaxException,
                        scope: me
                    }
                }
            }
        }, cfg)]);
    },

    onAjaxException: function(proxy, request, operation, eOpts) {

    }

});